#!/usr/bin/env python3
import argparse
import sys
import os

from rotate import rotate
from merge import merge
from extract import extract
from cache import cache
from convert import convertf_p, convertf
from snplot import snplot

parser = argparse.ArgumentParser(
    prog='mgen v26.6.14',
    add_help=False,
    description='Mehrgarh Genetics Toolkit',
    epilog='Copyright (c) 2025 Tushar Rakheja (The MIT License)'
)

parser.add_argument('op', nargs='?', default=os.getcwd(), help="The operation you want to perform ('merge', 'rotate', 'extract', 'cache', 'convertf', 'convertf_p', 'snplot')")

def main():
    global parser

    args, _ = parser.parse_known_args()

    if args.op == 'rotate':
        rotate.main()
    elif args.op == 'merge':
        merge.main()
    elif args.op == 'extract':
        extract.main()
    elif args.op == 'cache':
        cache.main()
    elif args.op == 'convertf_p':
        convertf_p.main()
    elif args.op == 'convertf':
        convertf.main()
    elif args.op == 'snplot':
        snplot.main()
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == '__main__':
    main()